/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the ThreatModelRepresentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreatModelRepresentation{}

// ThreatModelRepresentation struct for ThreatModelRepresentation
type ThreatModelRepresentation struct {
	Name string `json:"name" yaml:"name"`
	Id string `json:"id" yaml:"id"`
	Type string `json:"type" yaml:"type"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
	Attributes *map[string]string `json:"attributes,omitempty" yaml:"attributes,omitempty"`
}

// NewThreatModelRepresentation instantiates a new ThreatModelRepresentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreatModelRepresentation(name string, id string, type_ string) *ThreatModelRepresentation {
	this := ThreatModelRepresentation{}
	this.Name = name
	this.Id = id
	this.Type = type_
	return &this
}

// NewThreatModelRepresentationWithDefaults instantiates a new ThreatModelRepresentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreatModelRepresentationWithDefaults() *ThreatModelRepresentation {
	this := ThreatModelRepresentation{}
	return &this
}

// GetName returns the Name field value
func (o *ThreatModelRepresentation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ThreatModelRepresentation) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *ThreatModelRepresentation) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentation) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ThreatModelRepresentation) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ThreatModelRepresentation) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentation) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ThreatModelRepresentation) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ThreatModelRepresentation) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentation) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ThreatModelRepresentation) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ThreatModelRepresentation) SetDescription(v string) {
	o.Description = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ThreatModelRepresentation) GetAttributes() map[string]string {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]string
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentation) GetAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ThreatModelRepresentation) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]string and assigns it to the Attributes field.
func (o *ThreatModelRepresentation) SetAttributes(v map[string]string) {
	o.Attributes = &v
}

func (o ThreatModelRepresentation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreatModelRepresentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullableThreatModelRepresentation struct {
	value *ThreatModelRepresentation
	isSet bool
}

func (v NullableThreatModelRepresentation) Get() *ThreatModelRepresentation {
	return v.value
}

func (v *NullableThreatModelRepresentation) Set(val *ThreatModelRepresentation) {
	v.value = val
	v.isSet = true
}

func (v NullableThreatModelRepresentation) IsSet() bool {
	return v.isSet
}

func (v *NullableThreatModelRepresentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreatModelRepresentation(val *ThreatModelRepresentation) *NullableThreatModelRepresentation {
	return &NullableThreatModelRepresentation{value: val, isSet: true}
}

func (v NullableThreatModelRepresentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreatModelRepresentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


