/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the RepresentationElement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepresentationElement{}

// RepresentationElement struct for RepresentationElement
type RepresentationElement struct {
	Representation string `json:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"json:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation" yaml:"representation""`
	Id string `json:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"json:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id" yaml:"id""`
	Name *string `json:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"json:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty" yaml:"name,omitempty""`
	Position Position `json:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"json:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position" yaml:"position""`
	Size Size `json:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"json:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size" yaml:"size""`
	Attributes *map[string]string `json:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"json:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty" yaml:"attributes,omitempty""`
}

// NewRepresentationElement instantiates a new RepresentationElement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepresentationElement(representation string, id string, position Position, size Size) *RepresentationElement {
	this := RepresentationElement{}
	this.Representation = representation
	this.Id = id
	this.Position = position
	this.Size = size
	return &this
}

// NewRepresentationElementWithDefaults instantiates a new RepresentationElement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepresentationElementWithDefaults() *RepresentationElement {
	this := RepresentationElement{}
	return &this
}

// GetRepresentation returns the Representation field value
func (o *RepresentationElement) GetRepresentation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Representation
}

// GetRepresentationOk returns a tuple with the Representation field value
// and a boolean to check if the value has been set.
func (o *RepresentationElement) GetRepresentationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Representation, true
}

// SetRepresentation sets field value
func (o *RepresentationElement) SetRepresentation(v string) {
	o.Representation = v
}

// GetId returns the Id field value
func (o *RepresentationElement) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RepresentationElement) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RepresentationElement) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RepresentationElement) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepresentationElement) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RepresentationElement) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RepresentationElement) SetName(v string) {
	o.Name = &v
}

// GetPosition returns the Position field value
func (o *RepresentationElement) GetPosition() Position {
	if o == nil {
		var ret Position
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *RepresentationElement) GetPositionOk() (*Position, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *RepresentationElement) SetPosition(v Position) {
	o.Position = v
}

// GetSize returns the Size field value
func (o *RepresentationElement) GetSize() Size {
	if o == nil {
		var ret Size
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *RepresentationElement) GetSizeOk() (*Size, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *RepresentationElement) SetSize(v Size) {
	o.Size = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *RepresentationElement) GetAttributes() map[string]string {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]string
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepresentationElement) GetAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *RepresentationElement) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]string and assigns it to the Attributes field.
func (o *RepresentationElement) SetAttributes(v map[string]string) {
	o.Attributes = &v
}

func (o RepresentationElement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepresentationElement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["representation"] = o.Representation
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["position"] = o.Position
	toSerialize["size"] = o.Size
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullableRepresentationElement struct {
	value *RepresentationElement
	isSet bool
}

func (v NullableRepresentationElement) Get() *RepresentationElement {
	return v.value
}

func (v *NullableRepresentationElement) Set(val *RepresentationElement) {
	v.value = val
	v.isSet = true
}

func (v NullableRepresentationElement) IsSet() bool {
	return v.isSet
}

func (v *NullableRepresentationElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepresentationElement(val *RepresentationElement) *NullableRepresentationElement {
	return &NullableRepresentationElement{value: val, isSet: true}
}

func (v NullableRepresentationElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepresentationElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


