/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the MitigationInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MitigationInstance{}

// MitigationInstance struct for MitigationInstance
type MitigationInstance struct {
	Mitigation string `json:"mitigation" yaml:"mitigation"`
	State string `json:"state" yaml:"state"`
}

// NewMitigationInstance instantiates a new MitigationInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMitigationInstance(mitigation string, state string) *MitigationInstance {
	this := MitigationInstance{}
	this.Mitigation = mitigation
	this.State = state
	return &this
}

// NewMitigationInstanceWithDefaults instantiates a new MitigationInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMitigationInstanceWithDefaults() *MitigationInstance {
	this := MitigationInstance{}
	return &this
}

// GetMitigation returns the Mitigation field value
func (o *MitigationInstance) GetMitigation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mitigation
}

// GetMitigationOk returns a tuple with the Mitigation field value
// and a boolean to check if the value has been set.
func (o *MitigationInstance) GetMitigationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mitigation, true
}

// SetMitigation sets field value
func (o *MitigationInstance) SetMitigation(v string) {
	o.Mitigation = v
}

// GetState returns the State field value
func (o *MitigationInstance) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *MitigationInstance) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *MitigationInstance) SetState(v string) {
	o.State = v
}

func (o MitigationInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MitigationInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mitigation"] = o.Mitigation
	toSerialize["state"] = o.State
	return toSerialize, nil
}

type NullableMitigationInstance struct {
	value *MitigationInstance
	isSet bool
}

func (v NullableMitigationInstance) Get() *MitigationInstance {
	return v.value
}

func (v *NullableMitigationInstance) Set(val *MitigationInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableMitigationInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableMitigationInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMitigationInstance(val *MitigationInstance) *NullableMitigationInstance {
	return &NullableMitigationInstance{value: val, isSet: true}
}

func (v NullableMitigationInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMitigationInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


