/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the Mitigation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Mitigation{}

// Mitigation struct for Mitigation
type Mitigation struct {
	Id string `json:"id" yaml:"id"`
	Name string `json:"name" yaml:"name"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
	RiskReduction int `json:"riskReduction" yaml:"riskReduction"`
	Attributes *map[string]string `json:"attributes,omitempty" yaml:"attributes,omitempty"`
}

// NewMitigation instantiates a new Mitigation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMitigation(id string, name string, riskReduction int) *Mitigation {
	this := Mitigation{}
	this.Id = id
	this.Name = name
	this.RiskReduction = riskReduction
	return &this
}

// NewMitigationWithDefaults instantiates a new Mitigation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMitigationWithDefaults() *Mitigation {
	this := Mitigation{}
	return &this
}

// GetId returns the Id field value
func (o *Mitigation) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Mitigation) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Mitigation) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Mitigation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Mitigation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Mitigation) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Mitigation) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mitigation) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Mitigation) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Mitigation) SetDescription(v string) {
	o.Description = &v
}

// GetRiskReduction returns the RiskReduction field value
func (o *Mitigation) GetRiskReduction() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.RiskReduction
}

// GetRiskReductionOk returns a tuple with the RiskReduction field value
// and a boolean to check if the value has been set.
func (o *Mitigation) GetRiskReductionOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskReduction, true
}

// SetRiskReduction sets field value
func (o *Mitigation) SetRiskReduction(v int) {
	o.RiskReduction = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Mitigation) GetAttributes() map[string]string {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]string
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mitigation) GetAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Mitigation) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]string and assigns it to the Attributes field.
func (o *Mitigation) SetAttributes(v map[string]string) {
	o.Attributes = &v
}

func (o Mitigation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Mitigation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["riskReduction"] = o.RiskReduction
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullableMitigation struct {
	value *Mitigation
	isSet bool
}

func (v NullableMitigation) Get() *Mitigation {
	return v.value
}

func (v *NullableMitigation) Set(val *Mitigation) {
	v.value = val
	v.isSet = true
}

func (v NullableMitigation) IsSet() bool {
	return v.isSet
}

func (v *NullableMitigation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMitigation(val *Mitigation) *NullableMitigation {
	return &NullableMitigation{value: val, isSet: true}
}

func (v NullableMitigation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMitigation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


