/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the Size type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Size{}

// Size struct for Size
type Size struct {
	Width int `json:"width" yaml:"width"`
	Height int `json:"height" yaml:"height"`
}

// NewSize instantiates a new Size object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSize(width int, height int) *Size {
	this := Size{}
	this.Width = width
	this.Height = height
	return &this
}

// NewSizeWithDefaults instantiates a new Size object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSizeWithDefaults() *Size {
	this := Size{}
	return &this
}

// GetWidth returns the Width field value
func (o *Size) GetWidth() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *Size) GetWidthOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *Size) SetWidth(v int) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *Size) GetHeight() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *Size) GetHeightOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *Size) SetHeight(v int) {
	o.Height = v
}

func (o Size) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Size) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["width"] = o.Width
	toSerialize["height"] = o.Height
	return toSerialize, nil
}

type NullableSize struct {
	value *Size
	isSet bool
}

func (v NullableSize) Get() *Size {
	return v.value
}

func (v *NullableSize) Set(val *Size) {
	v.value = val
	v.isSet = true
}

func (v NullableSize) IsSet() bool {
	return v.isSet
}

func (v *NullableSize) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSize(val *Size) *NullableSize {
	return &NullableSize{value: val, isSet: true}
}

func (v NullableSize) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSize) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


