/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the ThreatModelRepresentationElement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreatModelRepresentationElement{}

// ThreatModelRepresentationElement struct for ThreatModelRepresentationElement
type ThreatModelRepresentationElement struct {
	Representation string `json:"representation" yaml:"representation"`
	Id string `json:"id" yaml:"id"`
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
	Attributes *map[string]string `json:"attributes,omitempty" yaml:"attributes,omitempty"`
}

// NewThreatModelRepresentationElement instantiates a new ThreatModelRepresentationElement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreatModelRepresentationElement(representation string, id string) *ThreatModelRepresentationElement {
	this := ThreatModelRepresentationElement{}
	this.Representation = representation
	this.Id = id
	return &this
}

// NewThreatModelRepresentationElementWithDefaults instantiates a new ThreatModelRepresentationElement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreatModelRepresentationElementWithDefaults() *ThreatModelRepresentationElement {
	this := ThreatModelRepresentationElement{}
	return &this
}

// GetRepresentation returns the Representation field value
func (o *ThreatModelRepresentationElement) GetRepresentation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Representation
}

// GetRepresentationOk returns a tuple with the Representation field value
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentationElement) GetRepresentationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Representation, true
}

// SetRepresentation sets field value
func (o *ThreatModelRepresentationElement) SetRepresentation(v string) {
	o.Representation = v
}

// GetId returns the Id field value
func (o *ThreatModelRepresentationElement) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentationElement) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ThreatModelRepresentationElement) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ThreatModelRepresentationElement) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentationElement) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ThreatModelRepresentationElement) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ThreatModelRepresentationElement) SetName(v string) {
	o.Name = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ThreatModelRepresentationElement) GetAttributes() map[string]string {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]string
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatModelRepresentationElement) GetAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ThreatModelRepresentationElement) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]string and assigns it to the Attributes field.
func (o *ThreatModelRepresentationElement) SetAttributes(v map[string]string) {
	o.Attributes = &v
}

func (o ThreatModelRepresentationElement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreatModelRepresentationElement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["representation"] = o.Representation
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullableThreatModelRepresentationElement struct {
	value *ThreatModelRepresentationElement
	isSet bool
}

func (v NullableThreatModelRepresentationElement) Get() *ThreatModelRepresentationElement {
	return v.value
}

func (v *NullableThreatModelRepresentationElement) Set(val *ThreatModelRepresentationElement) {
	v.value = val
	v.isSet = true
}

func (v NullableThreatModelRepresentationElement) IsSet() bool {
	return v.isSet
}

func (v *NullableThreatModelRepresentationElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreatModelRepresentationElement(val *ThreatModelRepresentationElement) *NullableThreatModelRepresentationElement {
	return &NullableThreatModelRepresentationElement{value: val, isSet: true}
}

func (v NullableThreatModelRepresentationElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreatModelRepresentationElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


