/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the TrustZoneRepresentationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrustZoneRepresentationsInner{}

// TrustZoneRepresentationsInner struct for TrustZoneRepresentationsInner
type TrustZoneRepresentationsInner struct {
	Representation string `json:"representation" yaml:"representation"`
	Id string `json:"id" yaml:"id"`
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
	Position *Position `json:"position,omitempty" yaml:"position,omitempty"`
	Size *Size `json:"size,omitempty" yaml:"size,omitempty"`
	Attributes *map[string]string `json:"attributes,omitempty" yaml:"attributes,omitempty"`
	File *string `json:"file,omitempty" yaml:"file,omitempty"`
	Line *int `json:"line,omitempty" yaml:"line,omitempty"`
	CodeSnippet *string `json:"codeSnippet,omitempty" yaml:"codeSnippet,omitempty"`
}

// NewTrustZoneRepresentationsInner instantiates a new TrustZoneRepresentationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrustZoneRepresentationsInner(representation string, id string) *TrustZoneRepresentationsInner {
	this := TrustZoneRepresentationsInner{}
	this.Representation = representation
	this.Id = id
	return &this
}

// NewTrustZoneRepresentationsInnerWithDefaults instantiates a new TrustZoneRepresentationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrustZoneRepresentationsInnerWithDefaults() *TrustZoneRepresentationsInner {
	this := TrustZoneRepresentationsInner{}
	return &this
}

// GetRepresentation returns the Representation field value
func (o *TrustZoneRepresentationsInner) GetRepresentation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Representation
}

// GetRepresentationOk returns a tuple with the Representation field value
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetRepresentationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Representation, true
}

// SetRepresentation sets field value
func (o *TrustZoneRepresentationsInner) SetRepresentation(v string) {
	o.Representation = v
}

// GetId returns the Id field value
func (o *TrustZoneRepresentationsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TrustZoneRepresentationsInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TrustZoneRepresentationsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TrustZoneRepresentationsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TrustZoneRepresentationsInner) SetName(v string) {
	o.Name = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *TrustZoneRepresentationsInner) GetPosition() Position {
	if o == nil || IsNil(o.Position) {
		var ret Position
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetPositionOk() (*Position, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *TrustZoneRepresentationsInner) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given Position and assigns it to the Position field.
func (o *TrustZoneRepresentationsInner) SetPosition(v Position) {
	o.Position = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *TrustZoneRepresentationsInner) GetSize() Size {
	if o == nil || IsNil(o.Size) {
		var ret Size
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetSizeOk() (*Size, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *TrustZoneRepresentationsInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given Size and assigns it to the Size field.
func (o *TrustZoneRepresentationsInner) SetSize(v Size) {
	o.Size = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *TrustZoneRepresentationsInner) GetAttributes() map[string]string {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]string
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *TrustZoneRepresentationsInner) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]string and assigns it to the Attributes field.
func (o *TrustZoneRepresentationsInner) SetAttributes(v map[string]string) {
	o.Attributes = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *TrustZoneRepresentationsInner) GetFile() string {
	if o == nil || IsNil(o.File) {
		var ret string
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetFileOk() (*string, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *TrustZoneRepresentationsInner) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *TrustZoneRepresentationsInner) SetFile(v string) {
	o.File = &v
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *TrustZoneRepresentationsInner) GetLine() int {
	if o == nil || IsNil(o.Line) {
		var ret int
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetLineOk() (*int, bool) {
	if o == nil || IsNil(o.Line) {
		return nil, false
	}
	return o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *TrustZoneRepresentationsInner) HasLine() bool {
	if o != nil && !IsNil(o.Line) {
		return true
	}

	return false
}

// SetLine gets a reference to the given int and assigns it to the Line field.
func (o *TrustZoneRepresentationsInner) SetLine(v int) {
	o.Line = &v
}

// GetCodeSnippet returns the CodeSnippet field value if set, zero value otherwise.
func (o *TrustZoneRepresentationsInner) GetCodeSnippet() string {
	if o == nil || IsNil(o.CodeSnippet) {
		var ret string
		return ret
	}
	return *o.CodeSnippet
}

// GetCodeSnippetOk returns a tuple with the CodeSnippet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustZoneRepresentationsInner) GetCodeSnippetOk() (*string, bool) {
	if o == nil || IsNil(o.CodeSnippet) {
		return nil, false
	}
	return o.CodeSnippet, true
}

// HasCodeSnippet returns a boolean if a field has been set.
func (o *TrustZoneRepresentationsInner) HasCodeSnippet() bool {
	if o != nil && !IsNil(o.CodeSnippet) {
		return true
	}

	return false
}

// SetCodeSnippet gets a reference to the given string and assigns it to the CodeSnippet field.
func (o *TrustZoneRepresentationsInner) SetCodeSnippet(v string) {
	o.CodeSnippet = &v
}

func (o TrustZoneRepresentationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrustZoneRepresentationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["representation"] = o.Representation
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Line) {
		toSerialize["line"] = o.Line
	}
	if !IsNil(o.CodeSnippet) {
		toSerialize["codeSnippet"] = o.CodeSnippet
	}
	return toSerialize, nil
}

type NullableTrustZoneRepresentationsInner struct {
	value *TrustZoneRepresentationsInner
	isSet bool
}

func (v NullableTrustZoneRepresentationsInner) Get() *TrustZoneRepresentationsInner {
	return v.value
}

func (v *NullableTrustZoneRepresentationsInner) Set(val *TrustZoneRepresentationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTrustZoneRepresentationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTrustZoneRepresentationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrustZoneRepresentationsInner(val *TrustZoneRepresentationsInner) *NullableTrustZoneRepresentationsInner {
	return &NullableTrustZoneRepresentationsInner{value: val, isSet: true}
}

func (v NullableTrustZoneRepresentationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrustZoneRepresentationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


