/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
)

// checks if the ComponentParent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentParent{}

// ComponentParent struct for ComponentParent
type ComponentParent struct {
	Component string `json:"component" yaml:"component"`
}

// NewComponentParent instantiates a new ComponentParent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentParent(component string) *ComponentParent {
	this := ComponentParent{}
	this.Component = component
	return &this
}

// NewComponentParentWithDefaults instantiates a new ComponentParent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentParentWithDefaults() *ComponentParent {
	this := ComponentParent{}
	return &this
}

// GetComponent returns the Component field value
func (o *ComponentParent) GetComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Component
}

// GetComponentOk returns a tuple with the Component field value
// and a boolean to check if the value has been set.
func (o *ComponentParent) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Component, true
}

// SetComponent sets field value
func (o *ComponentParent) SetComponent(v string) {
	o.Component = v
}

func (o ComponentParent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentParent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component"] = o.Component
	return toSerialize, nil
}

type NullableComponentParent struct {
	value *ComponentParent
	isSet bool
}

func (v NullableComponentParent) Get() *ComponentParent {
	return v.value
}

func (v *NullableComponentParent) Set(val *ComponentParent) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentParent) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentParent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentParent(val *ComponentParent) *NullableComponentParent {
	return &NullableComponentParent{value: val, isSet: true}
}

func (v NullableComponentParent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentParent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


