/*
Open Threat Model Specification

A Schema Definition for Open Threat Model https://github.com/iriusrisk/OpenThreatModel\"

API version: 0.1.0
Contact: info@cysoh.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otm

import (
	"encoding/json"
	"fmt"
)

// ComponentRepresentationsInner struct for ComponentRepresentationsInner
type ComponentRepresentationsInner struct {
	CodeRepresentation *CodeRepresentation
	DiagramRepresentation *DiagramRepresentation
	ThreatModelRepresentation *ThreatModelRepresentation
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ComponentRepresentationsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into CodeRepresentation
	err = json.Unmarshal(data, &dst.CodeRepresentation);
	if err == nil {
		jsonCodeRepresentation, _ := json.Marshal(dst.CodeRepresentation)
		if string(jsonCodeRepresentation) == "{}" { // empty struct
			dst.CodeRepresentation = nil
		} else {
			return nil // data stored in dst.CodeRepresentation, return on the first match
		}
	} else {
		dst.CodeRepresentation = nil
	}

	// try to unmarshal JSON data into DiagramRepresentation
	err = json.Unmarshal(data, &dst.DiagramRepresentation);
	if err == nil {
		jsonDiagramRepresentation, _ := json.Marshal(dst.DiagramRepresentation)
		if string(jsonDiagramRepresentation) == "{}" { // empty struct
			dst.DiagramRepresentation = nil
		} else {
			return nil // data stored in dst.DiagramRepresentation, return on the first match
		}
	} else {
		dst.DiagramRepresentation = nil
	}

	// try to unmarshal JSON data into ThreatModelRepresentation
	err = json.Unmarshal(data, &dst.ThreatModelRepresentation);
	if err == nil {
		jsonThreatModelRepresentation, _ := json.Marshal(dst.ThreatModelRepresentation)
		if string(jsonThreatModelRepresentation) == "{}" { // empty struct
			dst.ThreatModelRepresentation = nil
		} else {
			return nil // data stored in dst.ThreatModelRepresentation, return on the first match
		}
	} else {
		dst.ThreatModelRepresentation = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ComponentRepresentationsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ComponentRepresentationsInner) MarshalJSON() ([]byte, error) {
	if src.CodeRepresentation != nil {
		return json.Marshal(&src.CodeRepresentation)
	}

	if src.DiagramRepresentation != nil {
		return json.Marshal(&src.DiagramRepresentation)
	}

	if src.ThreatModelRepresentation != nil {
		return json.Marshal(&src.ThreatModelRepresentation)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableComponentRepresentationsInner struct {
	value *ComponentRepresentationsInner
	isSet bool
}

func (v NullableComponentRepresentationsInner) Get() *ComponentRepresentationsInner {
	return v.value
}

func (v *NullableComponentRepresentationsInner) Set(val *ComponentRepresentationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentRepresentationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentRepresentationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentRepresentationsInner(val *ComponentRepresentationsInner) *NullableComponentRepresentationsInner {
	return &NullableComponentRepresentationsInner{value: val, isSet: true}
}

func (v NullableComponentRepresentationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentRepresentationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


